In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = 'CreditScoring.csv'

In [3]:
df = pd.read_csv(data)

df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [4]:
df.columns = df.columns.str.lower()

df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [5]:
status_values = {1: 'ok', 2: 'default', 0: 'unknown'}
df.status = df.status.map(status_values)

home_values = {1: 'rent', 2: 'owner', 3: 'private', 4: 'ignore', 5: 'parents', 6: 'other', 0: 'unknown'}
df.home = df.home.map(home_values)

marital_values = {1: 'single', 2: 'married', 3: 'widow', 4: 'separated', 5: 'divorced', 0: 'unknown'}
df.marital = df.marital.map(marital_values)

records_values = {1: 'no', 2: 'yes', 0: 'unk'}
df.records = df.records.map(records_values)

job_values = {1: 'fixed', 2: 'part-time', 3: 'freelance', 4: 'others', 0: 'unknown'}
df.job = df.job.map(job_values)

df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [12]:
for column in ['income', 'assets', 'debt']:
    df[column] = df[column].replace(to_replace=99999999, value = np.nan)

df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4421.0,4408.0,4437.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,131.0,5403.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11573.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

In [13]:
df = df[df.status != 'unk'].reset_index(drop=True)

In [14]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = (df_train.status == 'default').astype(int)
y_val = (df_val.status == 'default').astype(int)
y_test = (df_test.status == 'default').astype(int)

del df_train['status']
del df_val['status']
del df_test['status']

In [15]:
df_train

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,14,owner,60,30,married,no,fixed,60,70.0,4000.0,2800.0,600,1125
1,2,parents,60,35,married,no,fixed,75,104.0,0.0,0.0,1200,1677
2,8,rent,36,61,single,no,fixed,42,72.0,0.0,0.0,325,450
3,14,owner,60,40,married,no,fixed,45,91.0,0.0,0.0,1100,1565
4,2,other,60,41,separated,no,freelance,35,100.0,5000.0,0.0,1200,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2668,6,owner,48,26,married,yes,fixed,35,90.0,5000.0,0.0,1390,1594
2669,5,owner,60,48,married,yes,fixed,90,100.0,2000.0,792.0,1000,1034
2670,28,owner,36,46,married,no,fixed,75,170.0,6000.0,0.0,750,800
2671,6,owner,48,35,married,no,freelance,60,0.0,3500.0,350.0,1300,1588
2672,7,owner,36,29,married,no,fixed,60,121.0,3000.0,0.0,650,915

In [18]:
def assess_risk(client):
    if client['records'] == 'yes':
        if client['job'] == 'part-time':
            return 'default'
        else:
            return 'ok'
    else:
        if client['assets'] > 6000:
            return 'ok'
        else:
            return 'default'

In [19]:
df_train.iloc[0].to_dict()

{'seniority': 14,
 'home': 'owner',
 'time': 60,
 'age': 30,
 'marital': 'married',
 'records': 'no',
 'job': 'fixed',
 'expenses': 60,
 'income': 70.0,
 'assets': 4000.0,
 'debt': 2800.0,
 'amount': 600,
 'price': 1125}

In [20]:
x_i = df_train.iloc[0].to_dict()
assess_risk(x_i)

'default'

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text

In [24]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

In [25]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [26]:
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [27]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [30]:
y_pred = dt.predict_proba(X_val)[:, 1]

In [31]:
roc_auc_score(y_val, y_pred)

0.6632819953659534

In [32]:
y_pred = dt.predict_proba(X_train)[:, 1]
roc_auc_score(y_train, y_pred)

0.9999996450431698

OVERFITTING!!!!!!!!!!!!!

In [33]:
y_train[0]

np.int64(0)

In [36]:
x_i

{'seniority': 14,
 'home': 'owner',
 'time': 60,
 'age': 30,
 'marital': 'married',
 'records': 'no',
 'job': 'fixed',
 'expenses': 60,
 'income': 70.0,
 'assets': 4000.0,
 'debt': 2800.0,
 'amount': 600,
 'price': 1125}

In [51]:
dt = DecisionTreeClassifier(max_depth = 2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [52]:
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train: ', auc)

y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('val: ', auc)

train:  0.6989678565292888
val:  0.6701804056649362

Even a model with max_depth = 2 performs better than an overfitted model

In [55]:
print(export_text(dt, feature_names=dv.get_feature_names_out()))

|--- records=no <= 0.50
|   |--- seniority <= 6.50
|   |   |--- class: 1
|   |--- seniority >  6.50
|   |   |--- class: 0
|--- records=no >  0.50
|   |--- job=part-time <= 0.50
|   |   |--- class: 0
|   |--- job=part-time >  0.50
|   |   |--- class: 1

In [56]:
some_data = [
    [8000, 'default'], 
    [2000, 'default'], 
    [0, 'default'], 
    [5000, 'ok'], 
    [5000, 'ok'], 
    [4000, 'ok'], 
    [9000, 'ok'], 
    [3000, 'default']
]

In [57]:
df_example = pd.DataFrame(some_data, columns=['assets', 'status'])
df_example

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

In [59]:
df_example.sort_values(by='assets')

   assets   status
2       0  default
1    2000  default
7    3000  default
5    4000       ok
4    5000       ok
3    5000       ok
0    8000  default
6    9000       ok

In [61]:
from IPython.display import display

In [66]:
Ts = [0, 2000, 3000, 4000, 5000, 8000]

In [67]:
for T in Ts:
    print(T)
    
    df_left = df_example[df_example.assets <= T]
    df_right = df_example[df_example.assets > T]

    display(df_left)
    display(df_right)

    print()

0

   assets   status
2       0  default

   assets   status
0    8000  default
1    2000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

2000

   assets   status
1    2000  default
2       0  default

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

3000

   assets   status
1    2000  default
2       0  default
7    3000  default

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok

4000

   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok

5000

   assets   status
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

   assets   status
0    8000  default
6    9000       ok

8000

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

   assets status
6    9000     ok